/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'merlin' at '31.03.17 10:23' with Gradle 2.14.1
 *
 * @author merlin, @date 31.03.17 10:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
